### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by frakman1** [a13xp0p0v/linux-kernel-defence-map#7]
I don't understand the relationship between this project and `kconfig-hardened-check`
I see that you have a `.dot` file that you use a tool (`dot`) to generate the `.svg` diagram from, but how do you generate the `.dot` file in the first place?
Can I use `kconfig-hardened-check` to generate such a diagram? I don't see a way to generate a `.dot` file from `kconfig-hardened-check`.

**Comment by a13xp0p0v** [comment]
Hello @frakman1,

The `.dot` file describing the Map is written manually.

And I created the `kconfig-hardened-check` tool to check some kernel options that you see at the Map.
